CREATE TABLE IF NOT EXISTS kitchens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_kitchens_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS sales_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    opened_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP WITH TIME ZONE NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS dishes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    kitchen_id BIGINT NULL,
    weight_grams INTEGER NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_dishes_name UNIQUE (name),
    CONSTRAINT fk_dishes_kitchen FOREIGN KEY (kitchen_id) REFERENCES kitchens(id)
);

CREATE INDEX IF NOT EXISTS idx_dishes_kitchen_id ON dishes(kitchen_id);

CREATE TABLE IF NOT EXISTS orders (
    id VARCHAR(36) PRIMARY KEY,
    table_no VARCHAR(20),
    notes VARCHAR(500),
    status VARCHAR(20) NOT NULL,
    total_items INTEGER NOT NULL DEFAULT 0,
    total_amount NUMERIC(10,2) NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_orders_status ON orders(status);
CREATE INDEX IF NOT EXISTS idx_orders_created_at ON orders(created_at);

CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id VARCHAR(36) NOT NULL,
    position INTEGER NOT NULL DEFAULT 0,
    name VARCHAR(120) NOT NULL,
    qty INTEGER NOT NULL DEFAULT 1,
    unit_price NUMERIC(10,2) NOT NULL DEFAULT 0,
    line_total NUMERIC(10,2) NOT NULL DEFAULT 0,
    item_note VARCHAR(300),
    CONSTRAINT fk_order_items_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items(order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_name ON order_items(name);

CREATE TABLE IF NOT EXISTS stats_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    total_orders BIGINT NOT NULL,
    total_dishes BIGINT NOT NULL,
    total_revenue NUMERIC(12,2) NOT NULL,
    new_orders BIGINT NOT NULL,
    in_progress_orders BIGINT NOT NULL,
    ready_orders BIGINT NOT NULL,
    done_orders BIGINT NOT NULL,
    dish_counters TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS kitchen_order_sequences (
    kitchen_id BIGINT PRIMARY KEY,
    current_value BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_kitchen_order_sequences_kitchen FOREIGN KEY (kitchen_id) REFERENCES kitchens(id)
);

CREATE TABLE IF NOT EXISTS customer_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR(60) NULL,
    order_note VARCHAR(1000) NULL,
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    sales_session_id BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customer_orders_sales_session FOREIGN KEY (sales_session_id) REFERENCES sales_sessions(id)
);

CREATE TABLE IF NOT EXISTS kitchen_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_order_id BIGINT NOT NULL,
    kitchen_id BIGINT NOT NULL,
    progressive_number BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    kitchen_total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    cancelled_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_kitchen_orders_customer_order FOREIGN KEY (customer_order_id) REFERENCES customer_orders(id),
    CONSTRAINT fk_kitchen_orders_kitchen FOREIGN KEY (kitchen_id) REFERENCES kitchens(id),
    CONSTRAINT uk_kitchen_orders_progressive UNIQUE (kitchen_id, progressive_number)
);

CREATE INDEX IF NOT EXISTS idx_kitchen_orders_kitchen_id ON kitchen_orders(kitchen_id);
CREATE INDEX IF NOT EXISTS idx_kitchen_orders_customer_order_id ON kitchen_orders(customer_order_id);
CREATE INDEX IF NOT EXISTS idx_kitchen_orders_status ON kitchen_orders(status);

CREATE TABLE IF NOT EXISTS order_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(120) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_order_options_label UNIQUE (label)
);

CREATE TABLE IF NOT EXISTS order_items_v2 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_order_id BIGINT NOT NULL,
    kitchen_order_id BIGINT NOT NULL,
    kitchen_id BIGINT NOT NULL,
    dish_id BIGINT NOT NULL,
    dish_name_snapshot VARCHAR(160) NOT NULL,
    qty INTEGER NOT NULL,
    unit_price_snapshot NUMERIC(12,2) NOT NULL,
    line_total NUMERIC(12,2) NOT NULL,
    weight_grams_snapshot INTEGER NULL,
    item_note VARCHAR(1000) NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_items_v2_customer_order FOREIGN KEY (customer_order_id) REFERENCES customer_orders(id),
    CONSTRAINT fk_order_items_v2_kitchen_order FOREIGN KEY (kitchen_order_id) REFERENCES kitchen_orders(id),
    CONSTRAINT fk_order_items_v2_kitchen FOREIGN KEY (kitchen_id) REFERENCES kitchens(id),
    CONSTRAINT fk_order_items_v2_dish FOREIGN KEY (dish_id) REFERENCES dishes(id)
);

CREATE INDEX IF NOT EXISTS idx_order_items_v2_customer_order_id ON order_items_v2(customer_order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_v2_kitchen_order_id ON order_items_v2(kitchen_order_id);
CREATE INDEX IF NOT EXISTS idx_order_items_v2_kitchen_id ON order_items_v2(kitchen_id);
CREATE INDEX IF NOT EXISTS idx_order_items_v2_dish_id ON order_items_v2(dish_id);

CREATE TABLE IF NOT EXISTS order_item_options (
    order_item_id BIGINT NOT NULL,
    option_id BIGINT NOT NULL,
    label_snapshot VARCHAR(120) NOT NULL,
    PRIMARY KEY (order_item_id, option_id),
    CONSTRAINT fk_order_item_options_item FOREIGN KEY (order_item_id) REFERENCES order_items_v2(id) ON DELETE CASCADE,
    CONSTRAINT fk_order_item_options_option FOREIGN KEY (option_id) REFERENCES order_options(id)
);

INSERT INTO kitchens (name, active, sort_order)
SELECT 'Panini', TRUE, 1
WHERE NOT EXISTS (SELECT 1 FROM kitchens WHERE name = 'Panini');

INSERT INTO kitchens (name, active, sort_order)
SELECT 'Cucina Dentro', TRUE, 2
WHERE NOT EXISTS (SELECT 1 FROM kitchens WHERE name = 'Cucina Dentro');

INSERT INTO sales_sessions (name, active)
SELECT 'Sessione di default', TRUE
WHERE NOT EXISTS (SELECT 1 FROM sales_sessions WHERE active = TRUE);

INSERT INTO kitchen_order_sequences (kitchen_id, current_value)
SELECT k.id, 0
FROM kitchens k
WHERE NOT EXISTS (
    SELECT 1 FROM kitchen_order_sequences s WHERE s.kitchen_id = k.id
);