-- Step 1: schema nuovo multi-cucina (compat legacy)

CREATE TABLE IF NOT EXISTS kitchens (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_kitchens_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS sales_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    opened_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP WITH TIME ZONE NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS kitchen_order_sequences (
    kitchen_id BIGINT PRIMARY KEY,
    current_value BIGINT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_kitchen_order_sequences_kitchen FOREIGN KEY (kitchen_id) REFERENCES kitchens(id)
);

CREATE TABLE IF NOT EXISTS customer_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    table_name VARCHAR(60) NULL,
    order_note VARCHAR(1000) NULL,
    total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    sales_session_id BIGINT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customer_orders_sales_session FOREIGN KEY (sales_session_id) REFERENCES sales_sessions(id)
);

CREATE TABLE IF NOT EXISTS kitchen_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_order_id BIGINT NOT NULL,
    kitchen_id BIGINT NOT NULL,
    progressive_number BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    kitchen_total_amount NUMERIC(12,2) NOT NULL DEFAULT 0,
    cancelled_at TIMESTAMP WITH TIME ZONE NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_kitchen_orders_customer_order FOREIGN KEY (customer_order_id) REFERENCES customer_orders(id),
    CONSTRAINT fk_kitchen_orders_kitchen FOREIGN KEY (kitchen_id) REFERENCES kitchens(id),
    CONSTRAINT uk_kitchen_orders_progressive UNIQUE (kitchen_id, progressive_number)
);

CREATE TABLE IF NOT EXISTS order_options (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    label VARCHAR(120) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    sort_order INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uk_order_options_label UNIQUE (label)
);


CREATE TABLE IF NOT EXISTS dishes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    price NUMERIC(10,2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_dishes_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS order_items_v2 (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_order_id BIGINT NOT NULL,
    kitchen_order_id BIGINT NOT NULL,
    kitchen_id BIGINT NOT NULL,
    dish_id BIGINT NOT NULL,
    dish_name_snapshot VARCHAR(160) NOT NULL,
    qty INTEGER NOT NULL,
    unit_price_snapshot NUMERIC(12,2) NOT NULL,
    line_total NUMERIC(12,2) NOT NULL,
    weight_grams_snapshot INTEGER NULL,
    item_note VARCHAR(1000) NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_items_v2_customer_order FOREIGN KEY (customer_order_id) REFERENCES customer_orders(id),
    CONSTRAINT fk_order_items_v2_kitchen_order FOREIGN KEY (kitchen_order_id) REFERENCES kitchen_orders(id),
    CONSTRAINT fk_order_items_v2_kitchen FOREIGN KEY (kitchen_id) REFERENCES kitchens(id),
    CONSTRAINT fk_order_items_v2_dish FOREIGN KEY (dish_id) REFERENCES dishes(id)
);

CREATE TABLE IF NOT EXISTS order_item_options (
    order_item_id BIGINT NOT NULL,
    option_id BIGINT NOT NULL,
    label_snapshot VARCHAR(120) NOT NULL,
    PRIMARY KEY (order_item_id, option_id),
    CONSTRAINT fk_order_item_options_item FOREIGN KEY (order_item_id) REFERENCES order_items_v2(id),
    CONSTRAINT fk_order_item_options_option FOREIGN KEY (option_id) REFERENCES order_options(id)
);

-- Seed cucine minime richieste
INSERT INTO kitchens (name, active, sort_order)
SELECT 'Panini', TRUE, 1
WHERE NOT EXISTS (SELECT 1 FROM kitchens WHERE name = 'Panini');

INSERT INTO kitchens (name, active, sort_order)
SELECT 'Cucina Dentro', TRUE, 2
WHERE NOT EXISTS (SELECT 1 FROM kitchens WHERE name = 'Cucina Dentro');

-- Seed sessione attiva di default
INSERT INTO sales_sessions (name, active)
SELECT 'Sessione di default', TRUE
WHERE NOT EXISTS (SELECT 1 FROM sales_sessions WHERE active = TRUE);

-- Seed sequenze cucina
INSERT INTO kitchen_order_sequences (kitchen_id, current_value)
SELECT k.id, 0
FROM kitchens k
WHERE NOT EXISTS (
    SELECT 1 FROM kitchen_order_sequences s WHERE s.kitchen_id = k.id
);
